const List daily = [
  {
    "icon": "assets/images/bank.png",
    "name": "Car Towing",
    "date": "Fri 10AM",
    "price": "\$340.00",
    "percent":"53%",
  },
  {
    "icon": "assets/images/auto.png",
    "name": "Car repair",
    "date": "Mon 8AM",
    "price": "\$70.00",
    "percent":"12%",
  },
  {
    "icon": "assets/images/gift.png",
    "name": "Car Fual",
    "date": "Sat 6PM",
    "price": "\$110.00",
    "percent":"12%",
  },
  {
    "icon": "assets/images/eating.png",
    "name": "Car Key Service",
    "date": "Sun 5PM",
    "price": "\$60.00",
    "percent":"17%",
  },
  {
    "icon": "assets/images/charity.png",
    "name": "Flate Tire",
    "date": "Wed 12PM",
    "price": "\$1200.00",
    "percent":"18%",
  },
   {
    "icon": "assets/images/bank.png",
    "name": "Car Towing",
    "date": "Fri 10AM",
    "price": "\$340.00",
    "percent":"53%",
  },
  {
    "icon": "assets/images/auto.png",
    "name": "Car repair",
    "date": "Mon 8AM",
    "price": "\$70.00",
    "percent":"12%",
  },
  {
    "icon": "assets/images/gift.png",
    "name": "Car Fual",
    "date": "Sat 6PM",
    "price": "\$110.00",
    "percent":"12%",
  },
  {
    "icon": "assets/images/eating.png",
    "name": "Car Key Service",
    "date": "Sun 5PM",
    "price": "\$60.00",
    "percent":"17%",
  },
  {
    "icon": "assets/images/charity.png",
    "name": "Flate Tire",
    "date": "Wed 12PM",
    "price": "\$1200.00",
    "percent":"18%",
  },
   {
    "icon": "assets/images/bank.png",
    "name": "Car Towing",
    "date": "Fri 10AM",
    "price": "\$340.00",
    "percent":"53%",
  },
  {
    "icon": "assets/images/auto.png",
    "name": "Car repair",
    "date": "Mon 8AM",
    "price": "\$70.00",
    "percent":"12%",
  },
  {
    "icon": "assets/images/gift.png",
    "name": "Car Fual",
    "date": "Sat 6PM",
    "price": "\$110.00",
    "percent":"12%",
  },
  {
    "icon": "assets/images/eating.png",
    "name": "Car Key Service",
    "date": "Sun 5PM",
    "price": "\$60.00",
    "percent":"17%",
  },
  {
    "icon": "assets/images/charity.png",
    "name": "Flate Tire",
    "date": "Wed 12PM",
    "price": "\$1200.00",
    "percent":"18%",
  }
];
